### ISSUE TITLE
Fix for the Time-Piece failed tests

### ISSUE THREAD

**Issue by JakeFromTheDark** [scottw/alpine-perl#2]
This command patches the `Time-Piece` tests with the extended timezone `EST5EDT4` definition:
```bash
sed 's!"EST5EDT4"!"EST5EDT4,M4.1.0/02:00:00,M10-5-0/02:00"!' \
  -i cpan/Time-Piece/t/02core_dst.t
```

Then the test passes:
```bash
./perl -I lib cpan/Time-Piece/t/02core_dst.t
```

as well as the whole Perl tests:
```bash
make test_harness
```

**Comment by scottw** [comment]
Thanks Jake—would you feel comfortable submitting this to the p5p? The goal is not that the Docker alpine-perl builds cleanly, but that *Perl* will build cleanly under Alpine Linux. What do you think?

**Comment by JakeFromTheDark** [comment]
no, don't feel that, sorry, because I have no idea what the p5p is.

**Comment by scottw** [comment]
> no, don't feel that, sorry, because I have no idea what the p5p is.

p5p is the Perl 5 Porters, the group responsible for Perl and its releases (including tests). The test you've identified as broken is a problem with Perl under any Alpine Linux distro. I think they'd be grateful to see your patch and may be willing to work with you to get it adopted into core Perl.

https://lists.perl.org/list/perl5-porters.html
