### ISSUE TITLE
loadable library and perl binaries are mismatched 

### ISSUE THREAD

**Issue by felsgaertner** [scottw/alpine-perl#4]
> SSLeay.c: loadable library and perl binaries are mismatched (got handshake key 0xce00080, needed 0xcd00080)

Hi, I am getting this error message since my last image build.

Dockerfile:
~~~dockerfile
FROM scottw/alpine-perl:latest

ENV PERL5LIB "/usr/share/perl5/vendor_perl:/usr/lib/perl5/vendor_perl"

RUN mkdir -p /docker
COPY /docker /docker

RUN chmod +x /docker/initialize.sh && /docker/initialize.sh

CMD ["/bin/bash"]
~~~

initialize.sh shell script:
~~~shell
#! /bin/sh

echo "Base upgrade OS"
apk update
#apk upgrade

echo "Add bash and openssl"
apk add bash
apk add openssl

echo "Add required perl modules"
apk add perl-yaml-tiny
apk add perl-net-ssleay
apk add perl-io-socket-ssl
cpanm -n GitLab::API::v4

echo "Add vendor modules to PERL5LIB"
echo "export PERL5LIB=$PERL5LIB" >> /root/.bashrc
~~~

My perl skript uses GitLab::API::v4, and this SSL connect fails now with the error mentioned above.

**Comment by felsgaertner** [comment]
The error occurs with and without that "apk upgrade" statement.

**Comment by scottw** [comment]
The native Alpine Perl packages (perl-yaml-tiny, etc) were built using Alpine's perl package, which has a different binary signature. You have two options:

1. Don't use scottw/alpine-perl as your base, use alpine as your base but install perl using apk (`apk add perl`)
2. Don't use the alpine Perl library packages, use cpanm to install them instead (`cpanm YAML::Tiny`, etc.)

**Comment by scottw** [comment]
If you do choose to use `cpanm` to install Perl packages (rather than the OS Perl packages via `apk`), I recommend using Alpine's libressl (and libressl-dev) packages rather than OpenSSL. I've had much better luck with libressl+libressl-dev when building Perl's crypto packages.
